### ISSUE TITLE
error: unknown option `color auto'

### ISSUE THREAD

**Issue by cedws** [mattmahn/gitall.rs#4]
I'm currently using d6df921e767c6845cc7f30c5c3ce732dc9ef3286.

Running `gitall -- branch --set-upstream-to=upstream/master master` causes git to throw an error for each subdirectory:

```
error: unknown option `color auto'
usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
   or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
   or: git branch [<options>] [-r] (-d | -D) <branch-name>...
   or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
   or: git branch [<options>] (-c | -C) [<old-branch>] <new-branch>
   or: git branch [<options>] [-r | -a] [--points-at]
   or: git branch [<options>] [-r | -a] [--format]
```

**Comment by mattmahn** [comment]
Thanks for the bug report!
You can try commit 99899dd (branch `color`) to see if it works or if there's a bigger issue going on.  I'll plan to tag a release around Thursday if there isn't some other issue.
